### ISSUE TITLE
Error in unalias

### ISSUE THREAD

**Issue by texastoland** [Homebrew/homebrew-aliases#24]
I just followed the readme:

```sh
❯ brew alias status='!git status'
❯ brew alias status              
brew alias status='!git status'
❯ brew unalias status       
Error: undefined method `named' for ["status"]:Array
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd/unalias.rb:22:in `unalias'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by bfontaine** [comment]
Thanks, there was an error in the arguments handling I just fixed: https://github.com/Homebrew/homebrew-aliases/commit/ca9e2e2f718d702cb431b1eeeb1c9ddbb22fba5a
